import { ExternalLink, Github } from "lucide-react";
const projects = [
  { number: "01", year: "2026", title: "RAG SYSTEM", subtitle: "AI", description: "An AI-powered document assistant built using Retrieval-Augmented Generation (RAG). Users can upload documents and ask questions in natural language. The system retrieves relevant document chunks using vector search and generates answers with source citations.", tags: ["Python", "RAG", "LLM", "Vector Search", "AI", "Machine Learning"], demo: "https://ragsystem.lovable.app", github: "https://github.com/Ankursaini018/ragsystem.git" },
  { number: "02", year: "2025", title: "SkinScan AI", subtitle: "DEEP LEARNING / HEALTHCARE", description: "AI-powered skin disease detection web application that detects skin diseases from uploaded images using deep learning and computer vision.", tags: ["Deep Learning", "Python", "Flask", "CNN"], github: "https://github.com/Ankursaini018/Skin-disease.git" },
  { number: "03", year: "2026", title: "SELF-SUPERVISED ANOMALY DETECTION / TIME SERIES", subtitle: "DEEP LEARNING / ANOMALY DETECTION", description: "A full-stack, self-supervised anomaly detection system for ECG time-series data using deep autoencoders. A React frontend and containerized backend analyze reconstruction errors to identify anomalies, combining deep learning with end-to-end application development.", tags: ["Deep Learning", "Time Series", "Autoencoders", "Self-Supervised Learning", "React", "Docker"], github: "https://github.com/Ankursaini018/deepanomaly-timeseries.git" },
];
const Projects = () => <section id="projects" className="diroz-section diroz-projects"><div className="diroz-shell">
  <div className="section-heading"><span className="section-index">/ 04 — SELECTED WORK</span><span>2025 — 2026</span></div>
  <h2 className="section-display">THE WORK<span>.</span></h2>
  <div className="projects-list">{projects.map(project => <article className="project-row" key={project.number}><div className="project-index"><span>{project.number} / 03</span><span>{project.year}</span></div><div className="project-content"><p className="project-category">{project.subtitle}</p><h3>{project.title}</h3><p className="project-description">{project.description}</p><div className="project-tags">{project.tags.map(tag => <span key={tag}>{tag}</span>)}</div><div className="project-links">{project.demo && <a href={project.demo} target="_blank" rel="noopener noreferrer"><ExternalLink /> LIVE DEMO</a>}<a href={project.github} target="_blank" rel="noopener noreferrer"><Github /> GITHUB</a></div></div></article>)}</div>
</div></section>;
export default Projects;
